from utils.errores.multiparidad.decode import decodeMultiparidad
from utils.errores.multiparidad.encode import encodeMultiparidad
from utils.errores.multiparidad.errors import detectarErrorMultiparidad, trySolveErrorMultiparidad
